import Head from 'next/head'
import {Box, Image, Button, Wrap, WrapItem, Stack, IconButton, Text} from '@chakra-ui/react' 
import {Select, Input} from '@chakra-ui/react'
import {CheckIcon} from '@chakra-ui/icons'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ubitec Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logored.png" />
      </Head>

      <main className={styles.main}>
       <div className={styles.rsection}>
        <div className={styles.fcontainer}>
          <Box>
            <Image className={styles.logo} src="https://ubitecglobal.com/wp-content/themes/ubitec/img/logo.png" alt='ubitec logo' width={200} height={200}/>
          </Box>
          <p className={styles.text}><strong>Lista de verificación: </strong> 
          identifique si su empresa necesita una plataforma de control vehicular.
          </p>
          <p className={styles.subtitle}>
            <strong>Optimice la gestión de su flotilla y disminuya costos usando una plataforma vehicular con tecnología GPS</strong>
          </p>
          <p className={styles.subtitle2}>
            Descargando nuestra lista de verificación, podrá descubrir 
            si esta es la solución que le ayudará a rentabilizar su flota vehicular.
          </p>
          <div className={styles.button}><Button colorScheme="blackAlpha" variant="solid" className={styles.btn}>Descargar lista de verificación</Button></div>
        </div>
            <Image className={styles.tablet} src="/tablet.png" alt='tablet' width={800} height={800}/>
       </div>
       <div className={styles.wsection}>
        <div className={styles.fcontainer}>
          <p className={styles.subtitle3}>Obtenga la lista de verificación llenando este formulario</p>
          <Input className={styles.textarea} placeholder='Nombre' size='lg' resize='none' w="80%"/>
          <Input className={styles.textarea} placeholder='Apellido' size='lg' resize='none' w="80%"/>
          <Input className={styles.textarea} placeholder='Correo Electrónico' size='lg' resize='none' w="80%"/>
          <Input className={styles.textarea} placeholder='Teléfono' size='lg' resize='none' w="80%"/>
          <Select placeholder='País' className={styles.textarea} size='lg' w="80%">

          </Select>
          <Select placeholder='¿Cuál es su rol de trabajo' className={styles.textarea} size='lg' w="80%">

          </Select>
          <Select placeholder='¿Cuál es su principal rol dentro de la empresa' className={styles.textarea} size='lg' w="80%">

          </Select>
          <div className={styles.button}><Button colorScheme="blackAlpha" variant="solid" className={styles.btn}>Obtener lista de verificación</Button></div>
        </div>
        <div className={styles.benefits}>
          <p className={styles.subtitle3}><strong>Complete la lista de verificación y usted podrá:</strong></p>
          <p className={styles.benefitext}><CheckIcon color="red"/>  
          Identificar si mantiene un control de rutas y recorridos de entrega de la forma adecuada.
          </p>
          <p className={styles.benefitext}><CheckIcon color="red"/>  
          Verificar si se encuentra informado de todas las actividades que realizan sus chofreres.
          </p>
          <p className={styles.benefitext}><CheckIcon color="red"/>  
          Conocer las actividades negativas que influyen en el aumento de costos.
          </p>
        </div>
       </div>
        <div className={styles.trsection}>
          <div className={styles.iconsb}>
          <Wrap justify='center'>
            <WrapItem h={210} w={700}>
          <div className={styles.lcontainer}>                                    
            <p className={styles.subtitle4}>Una plataforma de administración vehicular, de la mano con tecnología GPS, 
            brinda reportes de kilometrajes, rutas y posicionamiento en tiempo real para que mantenga un control permanente de sus flotas</p>
          </div>
          </WrapItem>
          <WrapItem>
          <Box h={410}>
            <Image className={styles.compu} src="/compu.png" alt='pc' width={567} height={410}/>
          </Box>
          </WrapItem>
          </Wrap>
          </div>
        </div>       
        <div className={styles.ttrsection} >
          <div className={styles.llcontainer}>
          <p className={styles.subtitle5}><strong>¿Cómo le beneficia una platafoma de administración y control vehicular?</strong></p>
          </div>        
          <div className={styles.iconsb}>
            <Stack direction={['column', 'row']} spacing='100px'>
              <Box>          
              <Image src="/img1.png" alt='img1' h={170} w={200} className={styles.licon}/>
              <Text fontSize='2xl'><strong>Estime tiempos de entrega</strong></Text>              
              </Box>
              <Box>
              <Image src="/img2.png" alt='img1' h={170} w={200} className={styles.licon}/>
              <Text className={styles.text2} fontSize='2xl'><strong>Defina el recorrido de sus flotas</strong></Text>
              </Box>
              <Box>
              <Image src="/img3.png" alt='img1' h={170} w={220} className={styles.licon}/>
              <Text className={styles.text2} fontSize='2xl'><strong>Verifique el estado de sus vehículos</strong></Text>
              </Box>
            </Stack>                     
            </div>
          <div className={styles.button2}><Button colorScheme="blackAlpha" variant="solid" className={styles.btn}>Obtener lista de verificación</Button></div>          
        </div>                
        <footer className={styles.footer}>
        <p className={styles.footertext}>Si estás interesado, puedes conocer más en <a href='https://ubitecglobal.com/'> <u>este enlace</u></a></p>        
      </footer>
      </main>
    </div>
  )
}
